// Run: NODE_PATH=<directory containing playwright> node tests/browser.cjs <demo root> <screenshots>
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('https://**/*', route => route.abort()); // Core delivery must work offline.
  const root = path.resolve(process.argv[2]);
  const shot = path.resolve(process.argv[3]); fs.mkdirSync(shot, {recursive: true});
  const url = f => pathToFileURL(path.join(root, f)).href;
  try {
    await page.goto(url('site/index.html'));
    await page.getByRole('link', {name: 'v1.1 · 批量完成', exact: true}).click();
    await page.getByRole('heading', {name: '需求差异'}).waitFor();
    assert.match(await page.locator('#content').innerText(), /新增.*FR-ORDER-003/);
    await page.locator('[data-version="v1.1"]').getByRole('link', {name: '订单列表', exact: true}).click();
    const frame = page.frameLocator('iframe');
    await frame.getByRole('button', {name: '本页需求', exact: true}).click();
    await frame.locator('.ps-panel').waitFor({state: 'visible'});
    assert.match(await frame.locator('.ps-panel').innerText(), /RULE-BATCH-COMPLETE/);
    assert.match(await frame.locator('.ps-panel').innerText(), /两条订单均变为已完成/);
    await frame.locator('#ps-inspect-select').selectOption('INT-BATCH');
    assert.match(await frame.locator('#ps-inspect-detail').innerText(), /RULE-BATCH-COMPLETE/);
    assert.doesNotMatch(await frame.locator('#ps-inspect-detail').innerText(), /RULE-NAME-INPUT/);
    await frame.locator('#ps-inspect-pending').check();
    assert.match(await frame.locator('#ps-inspect-detail').innerText(), /待确认/);
    await frame.locator('#ps-inspect-select').selectOption('INT-NAME');
    assert.equal(await frame.locator('#create-dialog').isVisible(), true);
    assert.match(await frame.locator('#ps-inspect-detail').innerText(), /仅含空格/);
    await frame.locator('#ps-close').click();
    await frame.locator('#cancel').click();
    await frame.locator('#ps-open').click();
    await frame.locator('#ps-inspect-pending').uncheck();
    await frame.locator('#ps-inspect-select').selectOption('INT-FEEDBACK');
    assert.match(await frame.locator('#ps-inspect-detail').innerText(), /未指定控件级规则/);
    await page.screenshot({path: path.join(shot, 'project-prototype.png'), fullPage: true});
    await page.goto(url('versions/v1.1/content/prototype/list.html'));
    await page.locator('#ps-reset').click();
    await page.locator('#create').click();
    await page.locator('#order-name').fill('浏览器验收订单');
    await page.locator('#submit').click();
    await page.locator('#create-dialog').waitFor({state: 'hidden'});
    assert.match(await page.locator('#rows').innerText(), /浏览器验收订单/);
    await page.locator('#detail').click();
    await page.locator('#detail-content').waitFor();
    assert.match(await page.locator('#detail-content').innerText(), /浏览器验收订单/);
    await page.locator('#back').click();
    await page.locator('#batch').click();
    assert.equal(await page.locator('#batch').isDisabled(), true);
    await page.locator('#ps-scenario').selectOption('error');
    await page.locator('#create').click(); await page.locator('#order-name').fill('失败后重试'); await page.locator('#submit').click();
    await page.locator('#form-error').filter({hasText: '提交失败'}).waitFor();
    assert.equal(await page.locator('#order-name').inputValue(), '失败后重试');
    await page.getByRole('button', {name: '查看弹框需求'}).click();
    assert.equal(await page.locator('dialog .ps-panel').isVisible(), true);
    await page.locator('#ps-close').click(); await page.locator('#cancel').click();
    await page.locator('#ps-scenario').selectOption('forbidden');
    assert.equal(await page.locator('#create').isDisabled(), true);
    await page.locator('#ps-scenario').selectOption('normal');
    await page.locator('#create').click();
    assert.equal(await page.locator('#order-name').inputValue(), '失败后重试');
    await page.locator('#submit').click();
    await page.locator('#create-dialog').waitFor({state:'hidden'});
    assert.equal(await page.locator('.order-row').filter({hasText:'失败后重试'}).count(), 1);
    await page.locator('#ps-scenario').selectOption('empty');
    assert.match(await page.locator('#feedback').innerText(), /暂无订单/);
    await page.locator('#ps-scenario').selectOption('loading');
    assert.equal(await page.locator('#create').isDisabled(), true);
    await page.locator('#ps-scenario').selectOption('normal');
    await page.locator('#ps-mode').click();
    await page.locator('.ps-marker').first().waitFor({state:'visible'});
    await page.locator('.ps-marker').first().click();
    await page.locator('#ps-note-view').waitFor({state:'visible'});
    assert.equal(await page.locator('#ps-note-form').isVisible(), false);
    assert.match(await page.locator('#ps-note-view-text').innerText(), /筛选订单/);
    await page.locator('[data-note-close]').first().click();
    await page.locator('#ps-edit-notes').click();
    await page.locator('#ps-note-add').click();
    await page.locator('#create').click({position:{x:20,y:20}});
    await page.locator('#ps-note-form').waitFor({state:'visible'});
    await page.locator('#ps-note-level').selectOption('warn');
    await page.locator('#ps-note-text').fill('手动补充：标题需随订单权限变化');
    await page.locator('#ps-note-form button[type=submit]').click();
    assert.match(await page.locator('#ps-note-status').innerText(), /已保存/);
    assert.ok(await page.locator('.ps-marker').filter({hasText:'M1'}).count(), '确认后应立即出现 M1 标记');
    const annotationKey = await page.evaluate(() => Object.keys(localStorage).find(key => key.startsWith('ps.annotations.')));
    const annotationState = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), annotationKey);
    assert.equal(annotationState.custom[0].selector, '#create');
    await page.locator('.ps-marker', {hasText:'M1'}).click();
    assert.match(await page.locator('#ps-note-view-text').innerText(), /标题需随订单权限变化/);
    assert.match(await page.locator('#ps-note-view-level').innerText(), /P1/);
    await page.locator('#ps-review-open').click();
    await page.locator('#ps-review-state').selectOption('accepted');
    await page.locator('#ps-review-note').fill('采纳交互建议');
    await page.locator('#ps-review-refs').fill('FR-ORDER-001');
    await page.getByRole('button',{name:'保存处理',exact:true}).click();
    await page.locator('#ps-review-read').filter({hasText:'已采纳'}).waitFor();
    await page.locator('#ps-review-open').click();
    await page.locator('#ps-review-state').selectOption('completed');
    await page.getByRole('button',{name:'保存处理',exact:true}).click();
    await page.locator('#ps-review-error').filter({hasText:'正式修改记录'}).waitFor();
    await page.locator('#ps-review-change').fill('review-demo-change');
    await page.locator('#ps-review-evidence').fill('人工验证原型操作');
    await page.getByRole('button',{name:'保存处理',exact:true}).click();
    await page.locator('#ps-review-read').filter({hasText:'已完成'}).waitFor();
    await page.screenshot({path:path.join(shot,'review-completed.png'),fullPage:true});
    await page.locator('[data-note-close]').first().click();
    await page.locator('#ps-edit-notes').click();
    await page.locator('#ps-review-filter').selectOption('completed');
    assert.equal(await page.locator('#ps-note-items article').count(),1);
    await page.locator('#ps-review-filter').selectOption('all');
    await page.locator('#ps-notes-close').click();
    await page.locator('.ps-marker', {hasText:'M1'}).click();
    await page.locator('#ps-note-view-edit').click();
    await page.locator('#ps-note-text').fill('手动补充：标题按角色显示');
    await page.locator('#ps-note-form button[type=submit]').click();
    await page.locator('.ps-marker', {hasText:'M1'}).click();
    assert.match(await page.locator('#ps-note-view-text').innerText(), /按角色显示/);
    assert.match(await page.locator('#ps-review-read').innerText(), /待处理/);
    await page.locator('#ps-note-view-delete').click();
    assert.equal(await page.locator('.ps-marker', {hasText:'M1'}).count(), 0);
    await page.locator('#ps-edit-notes').click();
    await page.locator('#ps-note-show-deleted').check();
    await page.locator('[data-note-action=restore]').last().click();
    await page.locator('#ps-notes-close').click();
    await page.locator('.ps-marker', {hasText:'M1'}).click();
    assert.match(await page.locator('#ps-note-view-text').innerText(), /按角色显示/);
    await page.locator('[data-note-close]').first().click();
    await page.locator('#ps-open').click();
    const before = await page.locator('.ps-panel').boundingBox();
    const header = await page.locator('.ps-panel-head strong').boundingBox();
    await page.mouse.move(header.x+20, header.y+10); await page.mouse.down(); await page.mouse.move(header.x-180, header.y+80, {steps: 8}); await page.mouse.up();
    const after = await page.locator('.ps-panel').boundingBox(); assert.ok(after.x < before.x - 100);
    await page.mouse.move(after.x + after.width - 3, after.y + after.height - 3); await page.mouse.down();
    await page.mouse.move(after.x + after.width + 55, after.y + after.height + 40, {steps:5}); await page.mouse.up();
    const resized = await page.locator('.ps-panel').boundingBox(); assert.ok(resized.width > after.width + 20);
    await page.locator('#ps-dock').click();
    assert.match(await page.locator('.ps-panel').getAttribute('class'), /ps-docked/);
    await page.screenshot({path:path.join(shot, 'standalone-panel.png'),fullPage:true});
    await page.goto(url('site/index.html') + '#/v/v1.0/prototype/order-list');
    assert.match(await page.locator('.project-history').innerText(), /历史版本 v1.0/);
    assert.equal(await page.frameLocator('iframe').locator('#batch').isVisible(), false);
    await page.screenshot({path:path.join(shot, 'history-v1.0.png'),fullPage:true});
    assert.deepEqual(errors, []);
    await page.goto(url('site/index.html') + '#/v/v1.1/requirements/spec');
    assert.match(await page.locator('#content').innerText(), /FR-ORDER-003/);
    console.log('PASS: version navigation, iframe/standalone panel, create/detail/return, batch, failure retention, permissions, modal review, annotations, drag/dock, history; no browser errors.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
