const {chromium} = require('playwright');
const {spawn, execFileSync} = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const {pathToFileURL} = require('node:url');
const assert = require('node:assert/strict');
(async () => {
  const root = path.resolve(process.argv[2]);
  const shots = path.resolve(process.argv[3]); fs.mkdirSync(shots, {recursive: true});
  // Test-only select fixture in the temporary project.
  const fixtureHtml = path.join(root, 'versions/v1.1/content/prototype/list.html');
  fs.writeFileSync(fixtureHtml, fs.readFileSync(fixtureHtml, 'utf8').replace('</main>', '<select id="edit-fixture"><option value="old">原选项</option></select></main>'));
  const fixtureSpec = path.join(root, 'versions/v1.1/content/spec.json');
  const fixture = JSON.parse(fs.readFileSync(fixtureSpec));
  fixture.interactions.push({id:'INT-FIXTURE', page:'order-list', selector:'#edit-fixture', requirement_ids:['FR-ORDER-001'], action:'input', description:'属性编辑测试选项'});
  fs.writeFileSync(fixtureSpec, JSON.stringify(fixture));
  execFileSync('python3', [path.join(root, 'build.py')]);
  const proc = spawn('python3', [path.join(__dirname, '../scripts/edit_project.py'), root, '--version', 'v1.1']);
  const url = await new Promise((resolve, reject) => {
    let output = '';
    proc.stdout.on('data', chunk => { output += chunk; const match = output.match(/http:\/\/127\.0\.0\.1:\d+\/#token=[\w-]+/); if (match) resolve(match[0]); });
    proc.once('exit', code => reject(new Error('编辑服务提前退出：' + code)));
    proc.once('error', reject);
  });
  const browser = await chromium.launch({headless: true});
  const page = await browser.newPage({viewport: {width: 1280, height: 900}});
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  try {
    await page.goto(url);
    await page.locator('#material').selectOption('it:INT-CREATE');
    await page.getByLabel('控件文案', {exact: true}).fill('创建新订单');
    await page.getByRole('button', {name: '预览变更', exact: true}).click();
    await page.getByRole('button', {name: '确认保存', exact: true}).click();
    await page.getByRole('status').filter({hasText: '已保存并重新编译'}).waitFor();
    const canvas = page.frameLocator('iframe');
    await canvas.locator('#search').click();
    await page.getByLabel('占位提示', {exact: true}).waitFor();
    assert.equal(await page.locator('#material').inputValue(), 'it:INT-SEARCH');
    await page.locator('#material').selectOption('it:INT-NAME');
    await page.getByLabel('最大长度', {exact: true}).fill('60');
    await page.getByLabel('占位提示', {exact: true}).fill('请输入订单名称');
    await page.getByLabel('宽度', {exact: true}).selectOption('full');
    await page.locator('#material').selectOption('it:INT-FIXTURE');
    await page.getByLabel('选项（每行 value=显示文字）', {exact: true}).fill('a=选项甲\nb=选项乙');
    await page.getByLabel('默认值', {exact: true}).fill('b');
    await page.getByLabel('必填', {exact: true}).selectOption('true');
    await page.locator('#material').selectOption('it:INT-DETAIL');
    await page.getByLabel('跳转或弹框目标', {exact: true}).selectOption('order-list');
    await page.locator('#material').selectOption('it:INT-NAME');
    await page.getByRole('button', {name: '预览变更', exact: true}).click();
    await page.getByRole('button', {name: '确认保存', exact: true}).click();
    await page.getByRole('status').filter({hasText: '已保存并重新编译'}).waitFor();
    const actual = await browser.newPage(); actual.on('pageerror', e => errors.push(e.message));
    await page.screenshot({path: path.join(shots, 'prototype-editor.png'), fullPage: true});
    await actual.goto(pathToFileURL(path.join(root, 'versions/v1.1/content/prototype/list.html')).href);
    await actual.getByRole('button', {name: '创建新订单', exact: true}).click();
    assert.equal(await actual.locator('#edit-fixture').inputValue(), 'b');
    assert.equal(await actual.locator('#edit-fixture').getAttribute('required'), '');
    assert.deepEqual(await actual.locator('#edit-fixture option').allTextContents(), ['选项甲','选项乙']);
    assert.equal(await actual.locator('#order-name').getAttribute('maxlength'), '60');
    assert.equal(await actual.locator('#order-name').getAttribute('placeholder'), '请输入订单名称');
    assert.equal(await actual.locator('#order-name').evaluate(node => node.style.width), '100%');
    await actual.locator('#order-name').fill('a'.repeat(50));
    await actual.locator('#submit').click();
    await actual.locator('#create-dialog').waitFor({state:'hidden'});
    assert.match(await actual.locator('#rows').innerText(), /a{50}/);
    await Promise.all([actual.waitForEvent('framenavigated'), actual.locator('#detail').click()]);
    await actual.waitForURL(/list\.html$/);
    await actual.close();
    await page.getByRole('button', {name: '撤销上次保存', exact: true}).click();
    await page.getByRole('status').filter({hasText: '已撤销'}).waitFor();
    const reverted = JSON.parse(fs.readFileSync(path.join(root, 'versions/v1.1/content/spec.json')));
    assert.equal(reverted.interactions.find(i => i.id === 'INT-NAME').properties, undefined);
    await page.locator('#material').selectOption('FR-ORDER-001');
    await page.getByLabel('需求标题', {exact: true}).fill('浏览器二次编辑订单');
    await page.getByRole('button', {name: '预览变更', exact: true}).click();
    await page.getByRole('button', {name: '确认保存', exact: true}).waitFor();
    assert.match(await page.locator('#impact').innerText(), /修改前/);
    await page.getByRole('button', {name: '确认保存', exact: true}).click();
    await page.getByRole('status').filter({hasText: '已保存并重新编译'}).waitFor();
    const spec = path.join(root, 'versions/v1.1/content/spec.json');
    assert.equal(JSON.parse(fs.readFileSync(spec)).requirements[0].title, '浏览器二次编辑订单');
    await page.reload();
    await page.getByLabel('需求标题', {exact: true}).waitFor();
    assert.equal(await page.getByLabel('需求标题', {exact: true}).inputValue(), '浏览器二次编辑订单');
    await page.getByLabel('需求标题', {exact: true}).fill('可撤销的订单标题');
    await page.getByRole('button', {name: '预览变更', exact: true}).click();
    await page.getByRole('button', {name: '确认保存', exact: true}).click();
    await page.getByRole('status').filter({hasText: '已保存并重新编译'}).waitFor();
    await page.getByRole('button', {name: '撤销上次保存', exact: true}).click();
    await page.getByRole('status').filter({hasText: '已撤销'}).waitFor();
    assert.equal(await page.getByLabel('需求标题', {exact: true}).inputValue(), '浏览器二次编辑订单');
    await page.getByLabel('需求标题', {exact: true}).fill('冲突时保留草稿');
    const overview = path.join(root, 'versions/v1.1/content/overview/index.md');
    fs.appendFileSync(overview, '\n人工编辑保留\n');
    await page.getByRole('button', {name: '预览变更', exact: true}).click();
    await page.getByRole('status').filter({hasText: '项目已被其他操作修改'}).waitFor();
    assert.equal(await page.getByLabel('需求标题', {exact: true}).inputValue(), '冲突时保留草稿');
    assert.match(fs.readFileSync(overview, 'utf8'), /人工编辑保留/);
    assert.equal(await page.getByRole('button', {name: '确认保存', exact: true}).isDisabled(), true);
    await page.screenshot({path: path.join(shots, 'editor-conflict.png'), fullPage: true});
    assert.deepEqual(errors, []);
    console.log('PASS: prototype point selection, text and constraints save, actual 50-character submission, undo; PRD edit, persisted reload and conflict protection; no browser errors');
  } finally { await browser.close(); proc.kill('SIGTERM'); }
})().catch(e => { console.error(e); process.exitCode = 1; });
